name = "serekes-1"
strategy = "bono"
log_level = "info"
key_file = ".key"
binance_history_secs = 300
chainlink_history_secs = 300
dvol_history_secs = 300
asset = "btc"
interval_minutes = 5
exchange_price_divergence_threshold = 50.0
log_interval_secs = 1.0